import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { RepoPicker } from '../RepoPicker';
import { Github, Pencil, Plus, Play, Terminal, Loader2, CheckCircle2, XCircle, KeyRound, Wrench, Sparkles, ArrowRight } from 'lucide-react';

interface Props { onOpenNewProject:()=>void; onOpenQuickBuild:()=>void; }
export const DashboardOverview: React.FC<Props> = ({onOpenNewProject,onOpenQuickBuild}) => {
 const {projects,builds,triggerBuild,setCurrentTab,subscription,repos,user,openRepo,selectRepo}=useApp();
 const [opening,setOpening]=useState('');const [openErr,setOpenErr]=useState('');
 const pick=async(repo:string)=>{setOpening(repo);setOpenErr('');const r=await openRepo(repo);setOpening('');if(!r.ok)setOpenErr(r.error||'Could not open that repository.')};
 const readOnly=(url:string)=>{const name=url.replace('https://github.com/','').replace(/\.git$/,'').toLowerCase();const r=repos.find(x=>x.fullName.toLowerCase()===name);return !!r&&!r.canPush};
 const [starting,setStarting]=useState<string|null>(null);
 const edit=(p:{kind?:string;repoUrl:string})=>{if(p.kind==='twa'){const n=p.repoUrl.replace('https://github.com/','').replace(/\.git$/,'');selectRepo(n);setCurrentTab('twa')}else setCurrentTab('projects')};
 const start=async(id:string)=>{setStarting(id);await triggerBuild(id);setStarting(null)};
 const latest=builds.slice(0,3);
 return <div className="max-w-5xl mx-auto p-4 sm:p-7 space-y-6">
   <section className="rounded-2xl border border-emerald-400/15 bg-gradient-to-b from-emerald-400/[.045] to-transparent p-5 sm:p-7">
    <div className="max-w-2xl"><div className="inline-flex items-center gap-2 text-[11px] text-emerald-300 font-semibold mb-3"><Sparkles className="w-3.5 h-3.5"/>LESS SETUP. MORE BUILDING.</div><h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-white">Repo in. Android build out.</h1><p className="mt-2 text-sm text-slate-400">WyBuild discovers your project, fills build settings, installs the workflow and keeps the logs in one place.</p></div>
    <div className="flex flex-wrap gap-2 mt-5"><button onClick={onOpenNewProject} className="h-11 px-4 rounded-xl bg-emerald-400 text-black font-bold text-sm flex items-center gap-2"><Github className="w-4 h-4"/>{projects.length?'Connect another repo':'Connect a repo'}</button>{projects.length>0&&<button onClick={onOpenQuickBuild} className="h-11 px-4 rounded-xl border border-emerald-400/20 text-emerald-200 font-semibold text-sm flex items-center gap-2"><Play className="w-4 h-4"/>Quick build</button>}</div>
   </section>

   {projects.length===0 ? <section className="rounded-2xl border border-white/[.06] bg-white/[.015] p-4 sm:p-5"><h2 className="text-white font-semibold">Pick a repository</h2><p className="mt-1 mb-3 text-sm text-slate-500">These are all the repos on your GitHub account. Tap one: WyBuild discovers it and takes you straight to the build.</p><RepoPicker onPick={pick} busyRepo={opening}/>{openErr&&<div className="mt-3 text-xs text-rose-300 p-3 rounded-lg bg-rose-500/[.06] border border-rose-500/20">{openErr}</div>}</section> : <section><div className="flex items-center justify-between mb-3"><h2 className="text-sm font-bold text-white">Your repos</h2><span className="text-xs text-slate-500">{projects.length}</span></div><div className="space-y-2">{projects.map(p=>{const b=builds.find(x=>x.projectId===p.id);return <div key={p.id} className="rounded-xl border border-white/[.06] bg-white/[.015] p-4 flex flex-col sm:flex-row sm:items-center gap-3"><div className="min-w-0 flex-1"><div className="font-semibold text-sm text-white truncate">{p.name}</div><div className="text-[11px] text-slate-500 font-mono truncate">{p.repoUrl.replace('https://github.com/','')} · {p.branch} · {p.config.target.toUpperCase()}</div>{readOnly(p.repoUrl)&&<div className="mt-1.5 text-[11px] text-amber-300">Read-only: signed in as {user?.login}, who cannot push to this repo, so WyBuild cannot install the workflow. Sign in as the owner, get write access, or connect a fork.</div>}</div><div className="flex items-center gap-2">{b?.status==='success'&&<CheckCircle2 className="w-4 h-4 text-emerald-300"/>}{b?.status==='failed'&&<XCircle className="w-4 h-4 text-rose-400"/>}<button onClick={()=>edit(p)} title="Edit version, package ID, native features and other app info, then rebuild" className="h-9 px-3 rounded-lg border border-emerald-400/20 text-emerald-200 font-semibold text-xs flex items-center gap-1.5"><Pencil className="w-4 h-4"/>Edit</button><button disabled={starting===p.id} onClick={()=>start(p.id)} className="h-9 px-3 rounded-lg bg-emerald-400 text-black font-bold text-xs flex items-center gap-1.5 disabled:opacity-50">{starting===p.id?<Loader2 className="w-4 h-4 animate-spin"/>:<Play className="w-4 h-4"/>}Build</button></div></div>})}</div></section>}

   <section className="grid grid-cols-2 sm:grid-cols-4 gap-2">
    <button onClick={()=>setCurrentTab('builds')} className="p-4 rounded-xl border border-white/[.06] bg-white/[.015] text-left"><Terminal className="w-4 h-4 text-emerald-300"/><div className="mt-2 text-sm text-white font-semibold">Logs</div><div className="text-[11px] text-slate-500">Build history</div></button>
    <button onClick={()=>setCurrentTab('tools')} className="p-4 rounded-xl border border-white/[.06] bg-white/[.015] text-left"><Wrench className="w-4 h-4 text-emerald-300"/><div className="mt-2 text-sm text-white font-semibold">Free tools</div><div className="text-[11px] text-slate-500">Still free</div></button>
    <button onClick={()=>setCurrentTab('settings')} className="p-4 rounded-xl border border-white/[.06] bg-white/[.015] text-left"><KeyRound className="w-4 h-4 text-emerald-300"/><div className="mt-2 text-sm text-white font-semibold">Keystore</div><div className="text-[11px] text-slate-500">Release signing</div></button>
    <button onClick={()=>setCurrentTab('billing')} className="p-4 rounded-xl border border-white/[.06] bg-white/[.015] text-left"><Sparkles className="w-4 h-4 text-emerald-300"/><div className="mt-2 text-sm text-white font-semibold">{subscription.plan==='pro'?'Pro':'Pro automation'}</div><div className="text-[11px] text-slate-500 flex items-center gap-1">{subscription.plan==='pro'?'Active':'See plan'}<ArrowRight className="w-3 h-3"/></div></button>
   </section>

   {latest.length>0&&<section><div className="flex items-center justify-between mb-3"><h2 className="text-sm font-bold text-white">Recent builds</h2><button onClick={()=>setCurrentTab('builds')} className="text-xs text-emerald-300">All logs</button></div><div className="rounded-xl border border-white/[.06] divide-y divide-white/[.05]">{latest.map(b=><div key={b.id} className="p-3 flex items-center justify-between gap-3"><div className="min-w-0"><div className="text-sm text-slate-200 truncate">{b.projectName}</div><div className="text-[11px] text-slate-500">{b.branch}</div></div><span className={`text-[11px] capitalize ${b.status==='success'?'text-emerald-300':b.status==='failed'?'text-rose-400':'text-amber-300'}`}>{b.status}</span></div>)}</div></section>}
 </div>
};
