import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { repoFromUrl } from '../../services/api';
import { Key, Plus, Trash2, LogOut } from 'lucide-react';

export const SettingsView: React.FC = () => {
  const { keystores, addKeystore, deleteKeystore, projects, user, logout } = useApp();
  const [showAdd, setShowAdd] = useState(false);
  const [name,setName]=useState(''); const [alias,setAlias]=useState(''); const [repo,setRepo]=useState('');
  const [storePassword,setStorePassword]=useState(''); const [keyPassword,setKeyPassword]=useState('');
  const [file,setFile]=useState<File|null>(null); const [saving,setSaving]=useState(false);
  const repos=Array.from(new Set(projects.map(p=>repoFromUrl(p.repoUrl)).filter((r):r is string=>!!r)));
  const save=async(e:React.FormEvent)=>{e.preventDefault();if(!name||!alias||!repo||!file)return;setSaving(true);const ok=await addKeystore({repo,name,alias,storePassword,keyPassword:keyPassword||storePassword,file});setSaving(false);if(ok){setShowAdd(false);setName('');setAlias('');setRepo('');setStorePassword('');setKeyPassword('');setFile(null);}};
  return <div className="max-w-3xl mx-auto p-4 sm:p-7 space-y-5">
    <div className="flex items-start justify-between gap-4"><div><h1 className="text-xl font-bold text-white">Keystore</h1><p className="text-sm text-slate-500 mt-1">Release signing keys are stored as encrypted GitHub Actions secrets.</p></div><button onClick={()=>setShowAdd(true)} disabled={!repos.length} className="h-10 px-3 rounded-lg bg-emerald-400 text-black font-bold text-xs flex items-center gap-1.5 disabled:opacity-40"><Plus className="w-4 h-4"/>Add</button></div>
    {!repos.length&&<div className="p-4 rounded-xl border border-white/[.06] bg-white/[.015] text-sm text-slate-500">Connect a repository before adding its signing key.</div>}
    <div className="space-y-2">{keystores.map(k=><div key={k.id} className="p-4 rounded-xl border border-white/[.06] bg-white/[.015] flex items-start justify-between gap-3"><div className="min-w-0"><div className="text-sm font-semibold text-white">{k.name}</div><div className="text-[11px] text-slate-500 font-mono mt-1">Alias: {k.alias}</div><div className="text-[10px] text-slate-600 font-mono break-all mt-1">{k.fingerprintSha256}</div></div><button onClick={()=>deleteKeystore(k.id)} className="p-2 text-slate-500 hover:text-rose-400"><Trash2 className="w-4 h-4"/></button></div>)}</div>
    {user&&<button onClick={logout} className="text-xs text-slate-500 flex items-center gap-2 hover:text-white"><LogOut className="w-4 h-4"/>Sign out {user.login}</button>}
    {showAdd&&<div className="fixed inset-0 z-50 bg-black/80 flex items-end sm:items-center justify-center"><form onSubmit={save} className="w-full sm:max-w-md rounded-t-2xl sm:rounded-2xl bg-[#07100d] border border-emerald-400/15 p-5 space-y-4"><div><h2 className="font-bold text-white">Add release keystore</h2><p className="text-xs text-slate-500 mt-1">WyBuild uploads it to GitHub Actions secrets for this repo.</p></div><select required value={repo} onChange={e=>setRepo(e.target.value)} className="w-full h-11 px-3 rounded-lg bg-black/30 border border-white/10 text-white"><option value="">Repository</option>{repos.map(r=><option key={r} value={r}>{r}</option>)}</select><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Key name" className="w-full h-11 px-3 rounded-lg bg-black/30 border border-white/10 text-white"/><input required value={alias} onChange={e=>setAlias(e.target.value)} placeholder="Alias" className="w-full h-11 px-3 rounded-lg bg-black/30 border border-white/10 text-white font-mono"/><input required type="file" accept=".jks,.keystore,.p12" onChange={e=>setFile(e.target.files?.[0]||null)} className="w-full text-sm text-slate-400"/><input required type="password" value={storePassword} onChange={e=>setStorePassword(e.target.value)} placeholder="Store password" className="w-full h-11 px-3 rounded-lg bg-black/30 border border-white/10 text-white"/><input type="password" value={keyPassword} onChange={e=>setKeyPassword(e.target.value)} placeholder="Key password (optional)" className="w-full h-11 px-3 rounded-lg bg-black/30 border border-white/10 text-white"/><div className="flex gap-2"><button type="button" onClick={()=>setShowAdd(false)} className="flex-1 h-11 rounded-lg border border-white/10 text-slate-300">Cancel</button><button disabled={saving} type="submit" className="flex-1 h-11 rounded-lg bg-emerald-400 text-black font-bold disabled:opacity-50">{saving?'Saving…':'Save'}</button></div></form></div>}
  </div>;
};
